id: P49EBAA4A
initial_creation_type: input
source_metadata:
  title: Drimé Ösal Lingpa Series
  language: es
  description: 'Texts by and about Tertön Drimé Ösal Lingpa (dri med ''od gsal gling
    pa):'
  volume:
    dd459d7e67ea49e8a6b999f2852322ea:
      title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab
        Lingpa
      parent: Prayers
created_at: '2022-02-28T23:04:53.524288'
last_modified_at: '2022-02-28T23:04:53.524290'
